In [10]:

import pybaseball_v5_function_copy as main_function
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



# Initialize a dictionary to store the results for each year
results = {}

# Iterate over the years
for year in range(2015, 2024):
    year_str = str(year)
    # Call the main function for the current year
    avg_class_report, avg_conf_matrix, bet_history, wallet_history = main_function.main_function(year_str)
    
    # Store the results in the dictionary
    results[year] = {
        'avg_class_report': avg_class_report,
        'avg_conf_matrix': avg_conf_matrix,
        'bet_history': bet_history,
        'wallet_history': wallet_history
    }

# Calculate the average of avg_class_report and avg_conf_matrix over all years
# Assuming avg_class_report and avg_conf_matrix are 2D arrays (matrices)
avg_class_report_all_years = np.mean([results[year]['avg_class_report'] for year in results], axis=0)
avg_conf_matrix_all_years = np.mean([results[year]['avg_conf_matrix'] for year in results], axis=0)

# Plot the data for each year
for year in results.keys():
    plt.figure(figsize=(10, 5))
    
    # Plot bet_history
    plt.subplot(1, 2, 1)
    plt.plot(results[year]['bet_history'])
    plt.title(f'Bet History {year}')
    
    # Plot wallet_history
    plt.subplot(1, 2, 2)
    plt.plot(results[year]['wallet_history'])
    plt.title(f'Wallet History {year}')
    
    plt.show()


KeyboardInterrupt: 

In [ ]:
results[year]['avg_class_report']

precision    recall  f1-score      support
0              0.575125  0.451890  0.505371  1164.000000
1              0.578949  0.692470  0.630289  1266.000000
accuracy       0.577229  0.577229  0.577229     0.577229
macro avg      0.577037  0.572180  0.567830  2430.000000
weighted avg   0.577117  0.577229  0.570452  2430.000000

In [ ]:
# Convert each year's avg_class_report to a DataFrame and use the implicit index
class_reports = [pd.DataFrame(results[year]['avg_class_report']) for year in results]

# Concatenate all DataFrames along the rows, ensuring that they align on the index
concatenated_reports = pd.concat(class_reports, axis=0)

# Group by the index (which is the implicit row labels) and calculate the mean
avg_class_report_all_years = concatenated_reports.groupby(concatenated_reports.index).mean()

print(avg_class_report_all_years)

              precision    recall  f1-score      support
0              0.566172  0.415592  0.469634  1053.333333
1              0.589131  0.720233  0.644475  1206.000000
accuracy       0.578394  0.578394  0.578394     0.578394
macro avg      0.577651  0.567913  0.557055  2259.333333
weighted avg   0.578728  0.578394  0.563219  2259.333333


In [ ]:
# Print just the macro average in the precision column
# Since class_reports is a list of DataFrames, we need to access each DataFrame individually
for year in results.keys():
    # Print the macro average in the precision column for each year
    print(f"Macro average precision for {year}: ", results[year]['avg_class_report'].loc['macro avg', 'precision'])
    
    # Print the confusion matrix for each year
    print(f"Confusion matrix for {year}: \n", results[year]['avg_conf_matrix'])

# Print the average confusion matrix over all years
print("Average confusion matrix over all years: \n", avg_conf_matrix_all_years)


Macro average precision for 2015:  0.5589633948495832
Confusion matrix for 2015: 
 [[ 367.66666667  746.33333333]
 [ 309.         1006.        ]]
Macro average precision for 2016:  0.5768255972278542
Confusion matrix for 2016: 
 [[ 319.          822.        ]
 [ 228.33333333 1058.66666667]]
Macro average precision for 2017:  0.5580553212427232
Confusion matrix for 2017: 
 [[ 329.66666667  788.33333333]
 [ 276.         1036.        ]]
Macro average precision for 2018:  0.5809734690203409
Confusion matrix for 2018: 
 [[563.33333333 584.66666667]
 [430.33333333 852.66666667]]
Macro average precision for 2019:  0.5903472002420679
Confusion matrix for 2019: 
 [[545.         598.        ]
 [393.66666667 892.33333333]]
Macro average precision for 2020:  0.5641582515837342
Confusion matrix for 2020: 
 [[220.33333333 177.66666667]
 [213.         287.        ]]
Macro average precision for 2021:  0.5825550917589525
Confusion matrix for 2021: 
 [[ 408.66666667  711.33333333]
 [ 299.33333333 1009.6

In [ ]:
# Convert each year's dictionary to a DataFrame and then calculate the mean
avg_class_report_all_years = pd.DataFrame([results[year]['avg_class_report'] for year in results]).mean()
avg_conf_matrix_all_years = pd.DataFrame([results[year]['avg_conf_matrix'] for year in results]).mean()

ValueError: Must pass 2-d input. shape=(9, 5, 4)

In [ ]:

avg_class_report_all_years = pd.concat([results[year]['avg_class_report'] for year in results]).groupby(level=0).mean()
avg_conf_matrix_all_years = pd.concat([results[year]['avg_conf_matrix'] for year in results]).groupby(level=0).mean()

TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid

In [ ]:
# # Get unique batter and pitcher ids from per_game_data
# batter_ids_per_game = per_game_data[batter_columns].values.flatten()
# pitcher_ids_per_game = per_game_data[pitcher_columns].values.flatten()

# # Check if these ids exist in the batter and pitcher data
# batter_ids_exist = batter_data['player_ID'].isin(batter_ids_per_game).any()
# pitcher_ids_exist = pitcher_data['player_ID'].isin(pitcher_ids_per_game).any()

# print(f"Do any batter ids in per_game_data exist in batter_data? {batter_ids_exist}")
# print(f"Do any pitcher ids in per_game_data exist in pitcher_data? {pitcher_ids_exist}")